name: Firebase Deployment

on:
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2.3.2

            - name: Set up Node.js 20.x
              uses: actions/setup-node@v2
              with:
                  node-version: "20.x"
                  cache: "npm"

            - name: Install Dependencies
              run: yarn

            - name: Build
              run: yarn build

            - name: Archive Production Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2.3.2

            - name: Download Artifact
              uses: actions/download-artifact@v2
              with:
                  name: dist
                  path: dist

            - name: Deploy to Firebase
              uses: firebase/firebase-tools-action@v1
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
